files:
  include: src/AnujRNair/AnujNairBundle/Resources/**/*.scss
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth:
    - 1
    - max-depth: 1
  border-zero:
    - 1
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: hyphenatedbem
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: false
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 1
    - include: true
  function-name-format:
    - 1
    - convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  id-name-format:
    - 1
    - convention: hyphenatedbem
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: true
  mixin-name-format:
    - 1
    - convention: hyphenatedlowercase
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 4
  no-color-keywords: 1
  no-color-literals: 0
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-zero: 1
  no-transition-all: 1
  placeholder-in-extend: 0
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order:
    - 1
    - order: concentric
  quotes:
    - 1
    - style: single
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-colon:
    - 1
    - include: true
  space-after-comma:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 1
  variable-name-format:
    - 1
    - convention: hyphenatedlowercase
  zero-unit: 1
