# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.assets_extension:
        class: AnujRNair\AnujNairBundle\Twig\AssetsExtension
        arguments:
            - @service_container
            - "%kernel.environment%"
        tags:
            - { name: twig.extension }
