<?php

namespace AnujRNair\AnujNairBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{

    public function getTagById($id)
    {
        return $this->getEntityManager()
            ->createQuery('
                select
                    t
                from AnujNairBundle:Tag as t
                where t.id = :id
            ')
            ->setParameters(['id' => $id])
            ->getSingleResult();
    }

    public function getTagSummary()
    {
        return $this->getEntityManager()
            ->createQuery('
                select
                    t.id,
                    t.name,
                    count(t.id) as tagCount
                from AnujNairBundle:Tag as t
                inner join t.tagMap as tm
                inner join tm.blog as b
                where t.deleted = 0
                and b.deleted = 0
                group by
                    t.id,
                    t.name
                order by t.name asc
            ')
            ->getResult();
    }

}
