_an_default:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /blog/
        permanent: true

_an_header:
    resource: "@AnujNairBundle/Controller/Components/HeaderController.php"
    type:     annotation

_an_footer:
    resource: "@AnujNairBundle/Controller/Components/FooterController.php"
    type:     annotation

_an_blog:
    resource: "@AnujNairBundle/Controller/BlogController.php"
    type:     annotation

_an_portfolio:
    resource: "@AnujNairBundle/Controller/PortfolioController.php"
    type:     annotation

_an_about:
    resource: "@AnujNairBundle/Controller/AboutController.php"
    type:     annotation

_an_admin:
    resource: "@AnujNairBundle/Controller/AdminController.php"
    type:     annotation

_an_sitemap:
    resource: "@AnujNairBundle/Controller/Components/SitemapController.php"
    type:     annotation