services:

    form.form_extention.icon:
        class: AnujRNair\AnujNairBundle\Forms\SubmitTypeIconExtension
        tags:
            - { name: form.type_extension, alias: submit }

    exception.handler:
        class: AnujRNair\AnujNairBundle\Listeners\Error\ExceptionHandler
        arguments:
            - @templating

    exception_listener:
        class: AnujRNair\AnujNairBundle\Listeners\Error\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 250 }
        arguments:
            - @exception.handler